### ISSUE TITLE
如何关闭拍摄时候的声音

### ISSUE THREAD

**Issue by hhyy1986** [BzCoder/SmartMediaPicker#10]

**Comment by BzCoder** [comment]
暂时没加，我加一下吧

**Comment by hhyy1986** [comment]
这个声音是写在那里呢，找了半天没有找到，连声音资源都没有

**Comment by BzCoder** [comment]
我查了下，声音不是在我这层发出来的，是在MediaRecorder中的，c++层的，并且没有暴露设置方法。。。。要禁用的话可以用野路子，比如录像的时候通过audiomanager直接把系统的声音给关了。

**Comment by hhyy1986** [comment]
哈哈，简单粗暴
