### ISSUE TITLE
 builder中必须要传入Fragment或者FragmentActivity？

### ISSUE THREAD

**Issue by maozhengjun** [BzCoder/SmartMediaPicker#11]
SmartMediaPicker.builder() builder中必须要传入Fragment或者FragmentActivity？想在react-native中使用,发现为了传入Fragment还要多写一个Activity😭，这样就导致多了一个原生界面
<img width="684" alt="image" src="https://user-images.githubusercontent.com/26665299/66910718-ac8d6980-f041-11e9-8209-ed748d051814.png">

**Comment by BzCoder** [comment]
rn我没怎么接触过，我这个fragment or fragmentactivity 主要是为了提供fragmentmanager用的，就是为了底部弹窗的，你rn可以调用native的弹窗么

**Comment by maozhengjun** [comment]
我不需要底部弹窗的 只需要录制视频，但是现在需要传入fragment，这就有点麻烦了😂

**Comment by BzCoder** [comment]
这个CurrentActivity可以转成FragmentActivity或者AppCompatActivity么

**Comment by maozhengjun** [comment]
转了也会报错：
 Exception in native call
    java.lang.IllegalStateException: Must be called from main thread of fragment host

**Comment by BzCoder** [comment]
这个是线程不对吧

**Comment by maozhengjun** [comment]
嗯 转换的话就报线程问题，现在也不知道还有啥办法，不加Activity就不行,唉
