### ISSUE TITLE
缺少requestCode怎么知道照片传给哪个事件？

### ISSUE THREAD

**Issue by czl0325** [BzCoder/SmartMediaPicker#16]
页面有多个SmartMediaPicker，你不用requestCode来区分？在onActivityResult里面你怎么知道是哪个SmartMediaPicker获取的照片？？？

**Comment by BzCoder** [comment]
看工具类。

**Comment by BzCoder** [comment]
这个需要自己改写下了，现在requestCode用于区分是拍照还是图片选择返回了。
