### ISSUE TITLE
在从手机相册选择时，全部哪里是没有把视频单独筛选出来吗；

### ISSUE THREAD

**Issue by Zaylour** [BzCoder/SmartMediaPicker#3]
因为我做的这个功能主要是选择视频上传，如果视频比较分散的话，不好找

**Comment by BzCoder** [comment]
由于现在是调用知乎图片选择器，日后改。

**Comment by BzCoder** [comment]
已在1.1.2中添加此功能，只要图片数目设置为0，视频设置为非0就可以只显示视频（图片同理）
