### ISSUE TITLE
视频录制的问题

### ISSUE THREAD

**Issue by 13307148979** [BzCoder/SmartMediaPicker#4]
1.视频录制不能指定文件夹保存吗？
2.视频录制的最大时长是多少，10s吗，怎么设置最大时长？

**Comment by BzCoder** [comment]
1.暂时没有指定文件夹功能
2.文档里有写
```
 //最大视频长度
                .withMaxVideoLength(15 * 1000)
                //最大视频文件大小 单位MB
                .withMaxVideoSize(1)
```

**Comment by 13307148979** [comment]
![TIM图片20190730144259](https://user-images.githubusercontent.com/31306341/62106760-a3a9b900-b2d8-11e9-8abd-c197056e0173.png)
根据您的demo，设置withMaxVideoLength(15 * 1000)，但是实际上视频时长还是10s，这行代码没起作用，上图是根据demo来的。还有设置withMaxVideoSize(1)，但实际上视频有2M。

**Comment by BzCoder** [comment]
谢谢使用，看了下确实是BUG，已在1.1.3中修复。随后发布。
