### ISSUE TITLE
前置摄像头拍摄有左右镜像问题，设置withIsMirror(true/false)都没用

### ISSUE THREAD

**Issue by workertao** [BzCoder/SmartMediaPicker#6]
前置摄像头拍摄有左右镜像问题，设置withIsMirror(true/false)都没用

**Comment by BzCoder** [comment]
收到，拍照镜像翻转一直都可以，经查看是录像翻转有问题，在新版本中会添加。

**Comment by BzCoder** [comment]
已经1.1.4中添加功能，如果需要使用需要额外引入以下库。如果使用中遇到Bug及时提出issue联系我。
```
//如果需要启用前置摄像头录像镜像调整功能需要额外引用以下库
implementation'com.github.MasayukiSuda:Mp4Composer-android:v0.3.2'
```

**Comment by workertao** [comment]
摄像没问题了，拍照又成左右镜像的了，看了下你的源码，你是在跳转的时候，设置是否镜像的，已经拍照了，是不是无法设置了。不知道咋改

**Comment by BzCoder** [comment]
> 
> 
> 摄像没问题了，拍照又成左右镜像的了，看了下你的源码，你是在跳转的时候，设置是否镜像的，已经拍照了，是不是无法设置了。不知道咋改

看了眼，是拍照和摄像逻辑写反了。我修改下。

**Comment by workertao** [comment]
现在可以了，感谢！
不过还有点小问题就是在拍摄完视频跳转播放的时候会卡顿1~2秒。

**Comment by BzCoder** [comment]
因为处理镜像的时候，进行了一次视频转码，所以有1-2秒的卡顿时间。暂时还没找到更好的解决方案。

**Comment by workertao** [comment]
好的，谢谢了！
