### ISSUE TITLE
录制时间过短会崩溃

### ISSUE THREAD

**Issue by xiongxiangdong** [BzCoder/SmartMediaPicker#7]
录制时间过短会崩溃

**Comment by BzCoder** [comment]
方便提供下错误信息吗

**Comment by xiongxiangdong** [comment]
![QQ图片20190907122158](https://user-images.githubusercontent.com/28045742/64469752-20e30c00-d16a-11e9-9965-45df4c3f07ed.png)
videoUrl为空．如果我设置为空不操作．又会引起其他问题．连续2次录制时间过短不能进行录制．

**Comment by xiongxiangdong** [comment]
可以确定有问题．我是直接下zip包．在多个手机下．都是报这个空指针

**Comment by BzCoder** [comment]
好的 谢谢 我周一看下 我会尽快修复的

**Comment by BzCoder** [comment]
已修复
