### ISSUE TITLE
大哥，你最新版本有问题啊

### ISSUE THREAD

**Issue by mcgradywu** [BzCoder/SmartMediaPicker#8]
当录屏长按，不管按多久都没反应，环形进度条也没走，把手移开，就提示录屏时间太短

**Comment by BzCoder** [comment]
我试了下 没有复现 你是否参数配置错误？

**Comment by mcgradywu** [comment]
同样的手机华为mate8 安卓8.0.0用SmartMediaPicker 1.1.1的版本就能录像，在1.1.6就不行

**Comment by BzCoder** [comment]
方便看下启动参数和gradle么

**Comment by mcgradywu** [comment]
classpath 'com.android.tools.build:gradle:3.3.2'
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip

**Comment by BzCoder** [comment]
implementation'com.github.MasayukiSuda:Mp4Composer-android:v0.3.2'引入了么

**Comment by mcgradywu** [comment]
引入了的

**Comment by BzCoder** [comment]
那么SmartMediaPicker.builder的参数呢

**Comment by mcgradywu** [comment]
SmartMediaPicker build = SmartMediaPicker.builder(appCompatActivity)
                //最大图片选择数目 如果不需要图片 将数目设置为0
                .withMaxImageSelectable(5)
                //最大视频选择数目 如果不需要视频 将数目设置为0
                .withMaxVideoSelectable(1)
                //图片选择器是否显示数字
                .withCountable(true)
                //最大视频长度
                .withMaxVideoLength(90000 * 1000)
                //最大视频文件大小 单位MB
                .withMaxVideoSize(20)
                //最大图片高度 默认1920
                .withMaxHeight(1920)
                //最大图片宽度 默认1920
                .withMaxWidth(1920)
                //最大图片大小 单位MB
                .withMaxImageSize(5)
                //设置图片加载引擎
                .withImageEngine(new Glide4Engine())
                //前置摄像头拍摄是否镜像翻转图像
                .withIsMirror(false)
                //弹出类别，默认弹出底部选择栏，也可以选择单独跳转
                .withMediaPickerType(MediaPickerEnum.BOTH)
                .build();

**Comment by mcgradywu** [comment]
发现问题了，.withMaxVideoLength(90000 * 1000)这个值设置的太大了，在1.1.6版本上就会出现问题，我改成300*1000就行了，我想问问你这个视频长度的临界值是多少？？？？

**Comment by BzCoder** [comment]
其实是没什么限制了，只是你总时间长了之后轮询时间会很久，导致进度更新一次会等很久
